export enum ROUTES {
  ROOT = '/',
  LOGIN = '/login',
  CONTACTUS = '/contactus',
  ABOUTUS = '/aboutus',
  CATEGORY = '/category',
  ALLPOSTS = '/allposts',
  CREATEPOST = '/createpost',
  BLOG = '/blog',
  PREVIEW = '/preview',
  DASHBOARD = '/dashboard',
  ANALYTICS = '/analytics',
  PROFILE = '/profile',
  AUTHOR = '/author',
  VERIFY_EMAIL = '/verify-email',
  OAUTH_CALLBACK = '/auth/callback',
}
